name: adventofcode
version: '0.1.0.0'
synopsis: Solutions for adventofcode
description: Please see the README on Github at <https://github.com/yogsototh/adventofcode#readme>
category: Web
author: Yann Esposito
maintainer: yann.esposito@gmail.com
copyright: ! 'Copyright: © 2017 Yann Esposito'
license: BSD3
github: yogsototh/adventofcode
extra-source-files:
- README.md
library:
  source-dirs: src
  exposed-modules:
  - Day01
  - Day02
  - Day03
  - Day04
  - Day05
  - Day06
  - Day07
  - Day08
  - Day09
  - Day10
  - Day11
  - Day12
  - Day13
  - Day14
  - Day15
  - Day16
  - Day17
  - Day18
  - Day19
  - Day20
  # - Day21
  # - Day22
  # - Day23
  # - Day24
  dependencies:
  - base >=4.7 && <5
  - protolude
  - containers
  - foldl
  - text
  - array
  - parsec
  - vector
  - lens
  - generic-lens
executables:
  adventofcode-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - base
    - adventofcode
    - protolude
    - pretty
    - containers
tests:
  adventofcode-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -O2
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - protolude
    - base
    - adventofcode
    - tasty
    - tasty-hunit
    - HUnit
